-- Diseño PostgreSQL/Supabase multiempresa. Aplicar solo en proyecto backend NUEVO.
create table tenants(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,settings jsonb default '{}'::jsonb,created_at timestamptz default now());
create table tenant_members(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,user_id uuid not null,role text not null check(role in('admin','sales','designer','production')),unique(tenant_id,user_id));
create table customers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,name text not null,phone text,email text,created_at timestamptz default now());
create table products(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,name text not null,category text,base_price numeric(12,2) default 0,template_url text,print_areas jsonb default '[]'::jsonb,active boolean default true);
create table projects(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,customer_id uuid references customers,title text,status text default 'draft',created_at timestamptz default now());
create table mockups(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,project_id uuid references projects on delete cascade,product_id uuid references products,preview_url text,placement jsonb,status text default 'draft',version int default 1,created_at timestamptz default now());
create table quotes(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,project_id uuid references projects,subtotal numeric(12,2) default 0,discount numeric(12,2) default 0,tax numeric(12,2) default 0,total numeric(12,2) default 0,status text default 'draft',created_at timestamptz default now());
create table quote_items(id uuid primary key default gen_random_uuid(),quote_id uuid not null references quotes on delete cascade,product_id uuid references products,description text,quantity numeric(12,2) not null default 1,unit_price numeric(12,2) not null default 0,total numeric(12,2) not null default 0);
create table approvals(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,mockup_id uuid references mockups on delete cascade,status text not null,comment text,approved_at timestamptz,created_at timestamptz default now());
create table orders(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants on delete cascade,quote_id uuid references quotes,status text default 'new',created_at timestamptz default now());
create index customers_tenant_idx on customers(tenant_id);create index products_tenant_idx on products(tenant_id);create index projects_tenant_idx on projects(tenant_id);create index mockups_tenant_idx on mockups(tenant_id);create index quotes_tenant_idx on quotes(tenant_id);create index orders_tenant_idx on orders(tenant_id);
