import React,{useState}from'react';
import{Building2,Users,Shirt,Image as ImageIcon,FileText,ShoppingBag,Plus,Upload,Send}from'lucide-react';
const demoProducts=[{id:1,name:'Playera clásica',category:'Textil',price:149},{id:2,name:'Taza 11 oz',category:'Promocional',price:89},{id:3,name:'Gorra',category:'Textil',price:129},{id:4,name:'Lona personalizada',category:'Gran formato',price:180},{id:5,name:'Hoja membretada',category:'Papelería',price:4}];
const modules=[['Clientes',Users],['Productos',Shirt],['Mockups',ImageIcon],['Cotizaciones',FileText],['Pedidos',ShoppingBag]];
export default function App(){
const[active,setActive]=useState('Inicio');const[clients,setClients]=useState(()=>{try{return JSON.parse(localStorage.getItem('msp_clients'))||[]}catch{return[]}});const[products]=useState(demoProducts);const[product,setProduct]=useState(demoProducts[0]);const[logo,setLogo]=useState('');const[size,setSize]=useState(35);const[x,setX]=useState(50);const[y,setY]=useState(50);const[qty,setQty]=useState(1);const[discount,setDiscount]=useState(0);const[proposals,setProposals]=useState(()=>{try{return JSON.parse(localStorage.getItem('msp_proposals'))||[]}catch{return[]}});const[orders,setOrders]=useState(()=>{try{return JSON.parse(localStorage.getItem('msp_orders'))||[]}catch{return[]}});
const addClient=()=>{const n=prompt('Nombre del cliente o empresa');if(n)setClients(v=>{const next=v.concat({id:Date.now(),name:n});localStorage.setItem('msp_clients',JSON.stringify(next));return next})};
const upload=e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=ev=>setLogo(ev.target.result);reader.readAsDataURL(f)};
const subtotal=product.price*qty;const total=subtotal*(1-discount/100);
const saveProposal=()=>{if(!logo)return;setProposals(v=>{const next=[{id:Date.now(),product:product.name,qty:qty,total:total,logo:logo,status:'Borrador'},...v];localStorage.setItem('msp_proposals',JSON.stringify(next));return next})};
const approve=id=>setProposals(v=>{const next=v.map(q=>q.id===id?{...q,status:'Aprobado'}:q);localStorage.setItem('msp_proposals',JSON.stringify(next));return next});const makeOrder=q=>setOrders(v=>{if(v.some(o=>o.proposalId===q.id))return v;const next=[{id:Date.now(),proposalId:q.id,product:q.product,qty:q.qty,total:q.total,status:'Nuevo'},...v];localStorage.setItem('msp_orders',JSON.stringify(next));return next});const share=()=>window.open('https://wa.me/?text='+encodeURIComponent('Propuesta '+product.name+' - '+qty+' piezas - $'+total.toFixed(2)+' MXN'),'_blank');
return <div className='app'><aside><div className='brand'><Building2/> MockupSales</div><small>Panel multiempresa</small><nav><button onClick={()=>setActive('Inicio')}>Inicio</button>{modules.map(([n,I])=><button key={n} onClick={()=>setActive(n)}><I size={18}/>{n}</button>)}</nav></aside><main><header><div><small>EMPRESA DEMO</small><h1>{active}</h1></div><button className='primary' onClick={()=>setActive('Mockups')}><Plus size={18}/>Nuevo proyecto</button></header>
{active==='Inicio'&&<Dashboard clients={clients} proposals={proposals} orders={orders}/>} 
{active==='Clientes'&&<section className='card'><h2>Clientes</h2><button className='primary' onClick={addClient}>Agregar cliente</button><div className='simplelist'>{clients.map(c=><div key={c.id}>{c.name}</div>)}</div></section>} 
{active==='Productos'&&<section className='card'><h2>Catálogo</h2><div className='products'>{products.map(p=><button key={p.id} onClick={()=>{setProduct(p);setActive('Mockups')}}><b>{p.name}</b><span>{p.category}</span><strong>{'$'+p.price}</strong></button>)}</div></section>} 
{active==='Mockups'&&<><section className='grid'><div className='card'><h2>Editor de mockup</h2><label className='drop'><Upload/><b>Cargar logo</b><input type='file' accept='image/*,.svg' onChange={upload}/></label><select value={product.id} onChange={e=>setProduct(products.find(z=>z.id===Number(e.target.value)))}>{products.map(z=><option value={z.id} key={z.id}>{z.name}</option>)}</select><label>Tamaño<input type='range' min='10' max='75' value={size} onChange={e=>setSize(Number(e.target.value))}/></label><label>Horizontal<input type='range' min='10' max='90' value={x} onChange={e=>setX(Number(e.target.value))}/></label><label>Vertical<input type='range' min='15' max='85' value={y} onChange={e=>setY(Number(e.target.value))}/></label><button className='primary' disabled={!logo} onClick={saveProposal}>Guardar propuesta</button><button onClick={share}><Send size={16}/>WhatsApp</button></div><div className='card'><h2>Vista previa</h2><div className='mock'><div className='productname'>{product.name}</div>{logo?<img src={logo} alt='Logo' style={{width:size+'%',left:x+'%',top:y+'%',transform:'translate(-50%,-50%)'}}/>:<span>LOGO</span>}<small>VISTA PREVIA · NO IMPRIMIR</small></div></div></section><section className='card'><h2>Historial</h2>{proposals.map(q=><div className='row' key={q.id}><div><b>{q.product}</b><small>{q.qty+' pzas · </div>)}</section></>} 
{active==='Cotizaciones'&&<section className='card'><h2>Cotización</h2><div className='quotecontrols'><label>Cantidad<input type='number' min='1' value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></label><label>Descuento %<input type='number' min='0' max='100' value={discount} onChange={e=>setDiscount(Math.min(100,Math.max(0,Number(e.target.value)||0)))}/></label></div><p>{'Subtotal: $'+subtotal.toFixed(2)}</p><h3>{'Total: $'+total.toFixed(2)+' MXN'}</h3><button onClick={share}>Compartir por WhatsApp</button></section>} 
{active==='Pedidos'&&<section className='card'><h2>Pedidos</h2>{orders.length===0?<p>Aprueba una propuesta para convertirla en pedido.</p>:orders.map(o=><div className='row' key={o.id}><div><b>{o.product}</b><small>{o.qty+' pzas · </main></div>}
function Dashboard({clients,proposals,orders}){const sum=proposals.reduce((a,q)=>a+q.total,0);return <><section className='stats'><div><b>{clients.length}</b><span>Clientes</span></div><div><b>{proposals.length}</b><span>Mockups</span></div><div><b>{'$'+sum.toFixed(0)}</b><span>Cotizado</span></div><div><b>{orders.length}</b><span>Pedidos</span></div></section><section className='grid'><div className='card'><h2>Venta visual</h2><p>Carga el logo, crea una propuesta y cotiza.</p></div><div className='card'><h2>Flujo comercial</h2><p>Cliente → Mockup → Cotización → Aprobación → Pedido</p></div></section></>}+q.total.toFixed(2)+' · '+(q.status||'Borrador')}</small></div><div className='actions'>{q.status!=='Aprobado'?<button onClick={()=>approve(q.id)}>Aprobar</button>:<button onClick={()=>makeOrder(q)}>Crear pedido</button>}</div></div>)}</section></>} 
{active==='Cotizaciones'&&<section className='card'><h2>Cotización</h2><div className='quotecontrols'><label>Cantidad<input type='number' min='1' value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></label><label>Descuento %<input type='number' min='0' max='100' value={discount} onChange={e=>setDiscount(Math.min(100,Math.max(0,Number(e.target.value)||0)))}/></label></div><p>{'Subtotal: $'+subtotal.toFixed(2)}</p><h3>{'Total: $'+total.toFixed(2)+' MXN'}</h3><button onClick={share}>Compartir por WhatsApp</button></section>} 
{active==='Pedidos'&&<section className='card'><h2>Pedidos</h2><p>Preparado para convertir propuestas aprobadas en órdenes.</p></section>}</main></div>}
function Dashboard({clients,proposals}){const sum=proposals.reduce((a,q)=>a+q.total,0);return <><section className='stats'><div><b>{clients.length}</b><span>Clientes</span></div><div><b>{proposals.length}</b><span>Mockups</span></div><div><b>{'$'+sum.toFixed(0)}</b><span>Cotizado</span></div><div><b>0</b><span>Pedidos</span></div></section><section className='grid'><div className='card'><h2>Venta visual</h2><p>Carga el logo, crea una propuesta y cotiza.</p></div><div className='card'><h2>Flujo comercial</h2><p>Cliente → Mockup → Cotización → Aprobación → Pedido</p></div></section></>}+o.total.toFixed(2)}</small></div><select value={o.status} onChange={e=>setOrders(v=>{const next=v.map(z=>z.id===o.id?{...z,status:e.target.value}:z);localStorage.setItem('msp_orders',JSON.stringify(next));return next})}><option>Nuevo</option><option>Producción</option><option>Listo</option><option>Entregado</option></select></div>)}</section>}</main></div>}
function Dashboard({clients,proposals}){const sum=proposals.reduce((a,q)=>a+q.total,0);return <><section className='stats'><div><b>{clients.length}</b><span>Clientes</span></div><div><b>{proposals.length}</b><span>Mockups</span></div><div><b>{'$'+sum.toFixed(0)}</b><span>Cotizado</span></div><div><b>0</b><span>Pedidos</span></div></section><section className='grid'><div className='card'><h2>Venta visual</h2><p>Carga el logo, crea una propuesta y cotiza.</p></div><div className='card'><h2>Flujo comercial</h2><p>Cliente → Mockup → Cotización → Aprobación → Pedido</p></div></section></>}+q.total.toFixed(2)+' · '+(q.status||'Borrador')}</small></div><div className='actions'>{q.status!=='Aprobado'?<button onClick={()=>approve(q.id)}>Aprobar</button>:<button onClick={()=>makeOrder(q)}>Crear pedido</button>}</div></div>)}</section></>} 
{active==='Cotizaciones'&&<section className='card'><h2>Cotización</h2><div className='quotecontrols'><label>Cantidad<input type='number' min='1' value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></label><label>Descuento %<input type='number' min='0' max='100' value={discount} onChange={e=>setDiscount(Math.min(100,Math.max(0,Number(e.target.value)||0)))}/></label></div><p>{'Subtotal: $'+subtotal.toFixed(2)}</p><h3>{'Total: $'+total.toFixed(2)+' MXN'}</h3><button onClick={share}>Compartir por WhatsApp</button></section>} 
{active==='Pedidos'&&<section className='card'><h2>Pedidos</h2><p>Preparado para convertir propuestas aprobadas en órdenes.</p></section>}</main></div>}
function Dashboard({clients,proposals}){const sum=proposals.reduce((a,q)=>a+q.total,0);return <><section className='stats'><div><b>{clients.length}</b><span>Clientes</span></div><div><b>{proposals.length}</b><span>Mockups</span></div><div><b>{'$'+sum.toFixed(0)}</b><span>Cotizado</span></div><div><b>0</b><span>Pedidos</span></div></section><section className='grid'><div className='card'><h2>Venta visual</h2><p>Carga el logo, crea una propuesta y cotiza.</p></div><div className='card'><h2>Flujo comercial</h2><p>Cliente → Mockup → Cotización → Aprobación → Pedido</p></div></section></>}